### ISSUE TITLE
hello to use the class output real change

### ISSUE THREAD

**Issue by djbdjb00djb** [talos/json_diff#1]
the comprae result would be like this http://tlrobinson.net/projects/javascript-fun/jsondiff/ 

the added key
the deled key
the added object
the deled object

it's not about the object ordinal number

**Comment by talos** [comment]
This is only a fork of the actual json_diff project, which is hosted here:

https://fedorahosted.org/json_diff

Please file all issues on their tracker:

https://fedorahosted.org/json_diff/report

Thanks!
